# Generated by Django 3.2.4 on 2021-07-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoounts', '0004_auto_20210707_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
