# Generated by Django 3.2.4 on 2021-07-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoounts', '0005_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_completen',
            new_name='is_completed',
        ),
    ]
